name = "lapce-json"
version = "0.1.1"
author = "abal1000x"
display-name = "Json"
description = "Formatter for JSON."
wasm = "lapce-json.wasm"
icon = "logo.svg"
repository = "https://github.com/abal1000x/lapce-json"

[activation]
language = ["json"]

[config."serverPath"]
default = ""
description = "Path to `vscode-json-language-server` executable. Install by `npm install -g vscode-html-languageserver-bin`."
