name = "lapce-json"
version = "0.1.0"
author = "abal1000x"
display-name = "Json"
description = "Formatter for JSON."
wasm = "lapce-json.wasm"
icon = "logo.svg"
repository = "https://github.com/abal1000x/lapce-json"

[activation]
language = ["json"]

[config."serverPath"]
default = ""
description = "Path to biome executable. When empty, it points to the bundled binary."
